image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

yarn:
  stage: .pre
  script: yarn

lint:
  stage: build
  script: yarn run lint
  allow_failure: false

test:
  stage: build
  script: yarn run test
  allow_failure: false

package:
  stage: build
  script:
    - yarn run sls:package
  artifacts:
    paths:
      - .serverless/
  allow_failure: false

# Deployment stages.

.deploy: &deploy
  script: yarn run sls:deploy:$CI_ENVIRONMENT_SLUG
  allow_failure: false
  only: [master]
  retry: 0

deploy_dev:
  stage: deploy
  environment: { name: dev }
  <<: *deploy

deploy_stage:
  stage: deploy
  environment: { name: stage }
  when: manual
  needs: [deploy_dev]
  <<: *deploy

deploy_prod:
  stage: deploy
  environment: { name: prod }
  when: manual
  needs: [deploy_stage]
  <<: *deploy
