image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - dev
  - stage
  - prod

build:
  stage: build
  script:
    - yarn
    - yarn run lint
    - yarn run test
    - yarn run sls:package

dev:
  stage: dev
  script: yarn run sls:deploy:dev
# stage:
#   stage: dev
#   script: serverless deploy --package ./.serverless --stage dev

# prod:
#   stage: dev
#   script: serverless deploy --package ./.serverless --stage dev
