image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy_dev
  - deploy_stage
  - deploy_prod

yarn:
  stage: .pre
  script: yarn

lint:
  stage: build
  script: yarn run lint

test:
  stage: build
  script: yarn run test

package:
  stage: build
  script:
    - yarn run sls:package
  artifacts:
    paths:
      - .serverless/

# Deployment stages.

.deploy: &deploy
  script: yarn run sls:deploy:$CI_ENVIRONMENT_SLUG
  allow_failure: false
  only: [master]
  retry: 0

deploy_dev:
  stage: deploy_dev
  environment: { name: dev }
  <<: *deploy

deploy_stage:
  stage: deploy_stage
  environment: { name: stage }
  when: manual
  <<: *deploy

deploy_prod:
  stage: deploy_prod
  environment: { name: prod }
  when: manual
  <<: *deploy
