name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - run: yarn run lint
    - run: yarn run test
    - run: serverless package
